repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
        name: Remove trailing whitespace
        description: This hook removes trailing whitespace from all files
        types: [text]
    -   id: end-of-file-fixer
        name: Fix end of files
        description: Ensures files end with a newline
        types: [text]
    -   id: check-yaml
        name: Check YAML syntax
        description: Validates YAML file syntax
    -   id: check-added-large-files
        name: Check for large files
        description: Prevents giant files from being committed

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
    -   id: ruff
        name: ruff
        description: Fast Python linter and formatter
        args: [--fix]
    -   id: ruff-format
        name: ruff-format
        description: Fast Python formatter

-   repo: local
    hooks:
    -   id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        types: [shell]
        args: ["--severity=warning"]
        files: \.sh$
