name: Lint

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    name: Run pre-commit checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install shellcheck and just
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck just

      - name: Install pipx and uv
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipx
          python -m pipx ensurepath
          pipx install uv
          uv tool install pre-commit

      - name: Run pre-commit
        run: |
          just lint
