name: Integration Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  test:
    name: Test Package Installation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install just
        run: |
          sudo apt-get update
          sudo apt-get install -y just

      - name: Run integration test
        run: just test-integration
